<nav>
    <select onchange="navigateTo(this.value)">
        <option value="">Select an Option...</option>
        <option value="index.php">Home</option>
        <option value="hikes.php">Hikes</option>
        <option value="add_hike.php">Add more</option>
        <option value="gallery.php">Gallery</option>
    </select>
    <img src="images/logo.png" alt="Logo" id="logo">
    <form>
        <input type="text" placeholder="Search...">
    </form>
</nav>
